// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecretMessageSharingWebApp.Data;

#nullable disable

namespace SecretMessageSharingWebApp.Migrations
{
    [DbContext(typeof(SecretMessagesDbContext))]
    [Migration("20220518120828_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SecretMessageSharingWebApp.Models.Entities.GetLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("RequestClientInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestCreatorIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SecretMessageCreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecretMessageCreatorClientInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretMessageCreatorIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SecretMessageExisted")
                        .HasColumnType("bit");

                    b.Property<string>("SecretMessageId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SecretMessageId");

                    b.ToTable("GetLogs");
                });

            modelBuilder.Entity("SecretMessageSharingWebApp.Models.Entities.SecretMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorClientInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatorIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DeleteOnRetrieve")
                        .HasColumnType("bit");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SecretMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
