// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecretMessageSharingWebApp.Data;

#nullable disable

namespace SecretMessageSharingWebApp.Migrations
{
    [DbContext(typeof(SecretMessageDbContext))]
    partial class SecretMessageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SecretMessageSharingWebApp.Models.DbContext.SecretMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorClientInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatorIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DeleteOnRetrieve")
                        .HasColumnType("bit");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SecretMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
