// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecretMessageSharingWebApp.Data;
using SecretMessageSharingWebApp.Repositories;

#nullable disable

namespace SecretMessageSharingWebApp.Migrations.GetLogsDb
{
    [DbContext(typeof(ISecretMessagesRepository))]
    partial class GetLogsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SecretMessageSharingWebApp.Models.DbContext.GetLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("RequestClientInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestCreatorIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SecretMessageCreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecretMessageCreatorClientInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretMessageCreatorIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SecretMessageExisted")
                        .HasColumnType("bit");

                    b.Property<string>("SecretMessageId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GetLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
